---
- name: Set default zone to public
  ansible.builtin.command: firewall-cmd --set-default-zone=public

- name: Disable SSH in public zone
  ansible.posix.firewalld:
    service: ssh
    zone: public
    permanent: true
    immediate: true
    state: disabled